react-monaco-editor/react-monaco-editor

- README.md
- package.json
- ~~drops reference to `tnpm`~~ no longer needed
- use `postinstall` hook to ensure `examples` dependencies are also up-to-date
- updated `README`
> cleanup initial experience

- README.md
- src/index.js
In 0.3.2, react-monaco-editor supports uncontrolled mode only.
In 0.4.0, it supports controlled mode only.
It is better to support both modes.
In this PR, use of `value` property enables controlled mode.
It is compatible with 0.4.0.
If he or she wants 0.3.2-compatible uncontrolled mode,
they can use `defaultValue` property instead of `value` property.
> Support both controlled and uncontrolled

- README.md
- src/index.js
This allow to specify a different context then the global window. 
Useful if you wish to load the editor inside an iframe, for example.
<MonacoEditor context={myIframe.contentWindow} />
This will append the needed ressources in the iframe, instead of the global window by default.
> Add a new context property

- package.json
A component never force consumer react version, if you want force a dependency on a specific version, use a peerDependency.
> Move react deps in dev

- .eslintrc
- examples/index.js
- examples/webpack.config.js
- package.json
- src/index.js
`eslint-config-rackt` is not in development anymore, in fact only a copy on `npmjs.com` does exists, its Github repository is gone.
Moved to `eslint-config-airbnb` and fixed most fo the linter's warnings. 
Some of them, specifically `react/require-default-props` and `react/no-string-refs` will need some refactoring of the code but at the moment it's not necessary.
> Move to ESLint's Airbnb config

- README.md
Fixes #22 
I decided to update the README instead of update the default property for the component because I don't know how many people are relying on the current behaviour.
> Fixed documented default value for height property

- README.md
Knowing the default value can help in the case that Monaco is available on a URL different than `<current_URL>/vs`
> Updated README with the default value for requiredConfig.path

- package.json
- src/index.js
Addresses #35 
This PR does the following:
- Bumps monaco version
- Replaces deprecated `theme` option
Full monaco-editor 0.9.0 changelog can be found [here](https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md)
> upgrade to monaco 0.9.0

- src/index.js
Similar to #31, changes to the onChange prop are ignored which can lead to odd behaviours. This fixes that.
> Fix treatment of onChange prop

- src/index.js
Removed string `ref` as per React documentation https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs
Is part of the fix for #27
> Removed string ref

- README.md
FIgure its worth adding this small note in case someone else runs into the same issue where `monaco-editor`'s async amd loading tries to find files from the relative path which may not be where webpack has copied the plugins to
> Update README with relative path loading fix

- README.md
- src/editor.js
This PR is in reference to my comment [here](https://github.com/superRaytin/react-monaco-editor/issues/75#issuecomment-350769720). It allows developers to override certain URLs (`loaderUrl` and `amdRequireBaseUrl`) even in Electron.
> Allow users to override loaderUrl and amdRequireBaseUrl even in Electron (refs #75)

- README.md
- examples/nextjs/.babelrc
- examples/nextjs/components/monaco-editor-wrapper.js
- examples/nextjs/next.config.js
- examples/nextjs/package.json
- examples/nextjs/pages/index.js
- examples/nextjs/pages/other-page.js
- examples/nextjs/server.js
There are several issues related to using monaco-editor in environments that have node-like globals defined, including  https://github.com/Microsoft/monaco-editor/issues/40. Next.js is such an environment.
It wasn't easy to get monaco-editor working with next.js, with or without react-monaco-editor, and when I did get it working, there were issues with switching pages.
Then I found @timkendrick's [distribution of monaco-editor](https://github.com/timkendrick/monaco-editor) and it worked once I added the CSS file and the global javascript variable.
In this PR is an example, that should work just by running `npm install` and `npm run dev`
> add next.js example, which uses CommonJS-friendly distribution of monaco editor

- examples/browser/package.json
- package.json
Microsoft released a new version of `monaco-editor`, which includes a number of enhancements to the editor API as well as support for ES modules. This PR updates `react-monaco-editor` to let package users enjoy the editor API enhancements, while leaving the import code as-is. This fixes #101, though a new issue may be needed for the internal cleanup @domoritz described in that issue's conversation.
While working on the repo, I hit a build error due to a dependency on babel's stage0 preset. This PR also adds that to `devDependencies` so that users will be able to run `npm install` without installing other packages.
> Update monaco-editor to 0.11.1

- src/diff.js
1. If `editorWillMount` es specified as non-existent (null or none), an exception is thrown.
2. [`IStandaloneDiffEditor#getModel()`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonediffeditor.html#getmodel) returns an [`IDiffEditorModel`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.idiffeditormodel.htm`) which is different from `ITextModel` that is accepted by `setModelLanguage`. It has two `ITextModel`s: `original` and `modified`. We have to set the language of both (or we can introduce the ability to have separate languages for each side).
3. `this.editorWillMount` doesn't take an argument, but is called with `monaco`.
> Fix some stuff in DiffEditor

- package.json
- src/diff.js
- src/editor.js
- src/utils/index.js
- src/utils/process-size.js
Hey! I like your project that `monaco-editor` very much!
But props of this editor have some problem, if i want to set `height` and `width` to `100px`, in the src,  they are process to `100pxpx`, that's fail! but the editor haven't "throw err" for this condition, It's hard for me to get better error messages to help debug. And sometimes, i want use `rem` or `rm` and other util, but editor can't process, because editor will add 'px' to end, value will to be '100rempx' or `100rmpx` and so on. It's hard to notice without looking at the source code.
I add a small function in util directory. There may be some things that I don't notice, but Enough to solve the problem.
Thank you for your editor, i like it, I want to keep contributing to it.
> Add process-size util for better process width and height

- src/editor.js
This is required to get JSON Schema working (must set model before instantiation)
> allow editorWillMount to set options

- src/diff.js
- src/editor.js
- src/index.d.ts
As mentioned in https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/43, this package causes Webpack to include the entire Monaco editor codebase in any build, even if only certain languages/features are desired.
With this change, only the core editor is imported, thus slimming down the build size considerably.
Resolves #142
> Only import the editor API instead of the whole package so that Webpack only loads relevant code

- src/index.d.ts
- test/typescript/editor.tsx
When creating a ref of the `MonacoEditor`, we need the `editor` property in the component's instance in order for the ref to work.
> Adds missing property in the component instance for React refs.

- .npmignore
There's a Yarn error log uploaded starting from version 0.21.0
https://cdn.jsdelivr.net/npm/react-monaco-editor@0.21.0/
> Don't upload yarn-error.log to npm package

- src/diff.js
Issue [#156](https://github.com/superRaytin/react-monaco-editor/issues/156) was fixed by PR [#162](https://github.com/superRaytin/react-monaco-editor/pull/162), but only in `editor.js`. This change also propagates the fix to `diff.js`, which is currently still not able to update options.
> Fix update options in diff

- src/editor.js
As documented [here](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#executeedits), `executeEdits` is the right way to edit  text while preserving the undo-redo stack. The previous code uses `setValue` which discards the undo-redo stack, preventing undo operations.
> Fix #211: keep undo states

- src/diff.js
- src/editor.js
Avoiding `ModelService: Cannot add model because it already exists!` error on unmounting and remounting.
> Store model reference to dispose on unmount

- src/diff.js
- src/editor.js
My current project has multiple react-monaco-editors on the same page. Each editor may use multiple models and some share models. I currently reuse models between different editors. When I unmount the editors it creates an error: 
This small change fixes it.
> Check model existence before disposing

- src/diff.js
Disposing the model before the editor causes an error after unmounting, after performing an action that pops up a widget like `ctrl + f` 
```
Canceled: Canceled
at Module.canceled 
at Delayer../node_modules/monaco-editor/esm/vs/base/common/async.js.Delayer.cancel 
at Object.dispose 
at Array.forEach (<anonymous>)
at dispose 
at FindWidget../node_modules/monaco-editor/esm/vs/base/common/lifecycle.js.Disposable.dispose 
at Array.forEach (<anonymous>)
```
The change in https://github.com/react-monaco-editor/react-monaco-editor/pull/253 fixes this for the normal editor, but the same fix needs to be applied to the diff viewer.
> Fix crash after diff viewer unmount

- src/index.d.ts
This makes type of options match the monaco editor API for create: https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#create. The old types prevented passing some valid options such as `model` or `wordBasedSuggestions`. This change also makes the typings consistent with this change: https://github.com/react-monaco-editor/react-monaco-editor/pull/265
> Update options to IStandaloneEditorConstructionOptions

- src/editor.js
Fixes #293. I can confirm locally IE 11 renders the example page just fine.
> Used spread instead of Object.assign in editor initMonaco

- package.json
- src/diff.tsx
- src/editor.tsx
- tsconfig.json
- yarn.lock
We're adopting `react-monaco-editor`. First of all, thanks! It's been a blast to use and solved a lot of quirks we had manually integrating Monaco into a React app.
We had some trouble due to the way the TS bindings are set up, however. I understand the JS->TS move is relatively recent so maybe these are just quirks that need to be ironed out? Let me know if any of the changes I'm proposing here are stupid or break something else I hadn't expected :-)
1. Fix react/prop-types imports. Without this PR, TypeScript users of react-monaco-editor would need to have allowSyntheticDefaultImports to be on in their tsconfig, or there would be TS errors due to the way React was being imported. As far as I can tell, simply moving those lines to `import * as React` was all that's needed to make it all …
> Improve dev experience for TypeScript users

- src/types.ts
The description of the property height is not matching the default value set which is `100%`. As shows [in this line of code](https://github.com/react-monaco-editor/react-monaco-editor/blob/d16df27a0da0819168c3b349ae237fa1035aedec/src/editor.tsx#L24).
I do not know if the decision of the default value was initially `500` or `100%` so I decided to make the change on the description and maybe open a discussion about it.
> Fix description of property height

- src/diff.tsx
- src/editor.tsx
- src/types.ts
ref https://github.com/react-monaco-editor/react-monaco-editor/issues/319
Allows for a `className` prop on the editor, and diff editor, which then bubbles into `options. extraEditorClassName`
If `options. extraEditorClassName` were also set, that will override the `className` prop, making this backwards-compatible.
To test this, I built the lib, copied it into `examples/node_modules/react-monaco-editor/lib`, then modified my local example to add `className="an-extra-class-here"`, and verified it showed up in the inspector.
```jsx
<MonacoEditor
height="400"
language="javascript"
className="an-extra-class-here"
value={code}
options={options}
onChange={this.onChange}
editorDidMount={this.editorDidMount}
theme={theme}
/>
```
> feat: allow className prop, to set options.extraEditorClassName

- README.md
Refer to [editor.create](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#create), `editor.create` accepts  an option as `monacoEditor.editor.IStandaloneEditorConstructionOptions`.
> docs: update options

- package.json
This will prevent "unmet peer" warnings for projects using React v18. I'm thinking we should allow this since the example within the repo is using React v18.
> Update `peerDependencies` to allow React v17 and v18

- src/diff.tsx
- src/editor.tsx
It fixes #655, also addresses #640.
The fix is to initialize the editor (by`initMonaco`) only when the component is mounted, and dispose the editor only before it's unmounted, as the props updating is already handled by perspective side effects.
> fixed issue of initializing editor multiple times

- package.json
Noticed this peer dep error:
```
❯ yarn explain peer-requirements pe94ca
➤ YN0000: studio@workspace:packages/studio provides react@npm:16.14.0 with version 16.14.0, which doesn't satisfy the following requirements:
➤ YN0000: @org/dashboard-editors@npm:25.1.0     → ^16.11.0 ✓
➤ YN0000: @org/dynamic-editors@npm:0.21.5       → ^16.11.0 ✓
➤ YN0000: @org/react-search@npm:4.0.1           → ^16.8    ✓
➤ YN0000: @org/react-time-range@npm:8.1.0       → ^16.10.0 ✓
➤ YN0000: @org/themes@npm:0.12.0                → ^16.8    ✓
➤ YN0000: @org/themes@npm:0.7.0                 → ^16.8    ✓
➤ YN0000: react-mde@npm:11.5.0                  → ^17.0.0  ✘
➤ YN0000: react-monaco-editor@npm:0.45.0        → ^17.x    ✘
```
I've been using `react-monaco-editor` for a long time on React 16 and haven't had any …
> Allow a wider version range for React

- src/editor.tsx
This avoids a flicker caused by Monaco needlessly resetting the content and performing syntax highlighting again.
Fixes #689
> fix: Don't set the Monaco value if it hasn't changed

- README.md
`IEditorOverrideServices` and `IEditor` links in the README are broken.
> chore: fix broken links in README.md

- src/editor.tsx
This PR removes explicit model deletion during unmounting.
Conceptually `IDisposable` cleans up everything within the object. Since the current code invokes `getModel` after `dispose`, there may be no guarantee to work.
At the implementation level, [`StandaloneEditor.dispose` eventually detaches the model (with invocation of the model's `dispose`)](https://github.com/microsoft/vscode/blob/3b60c12380f5a9782439be309d8d2642835b8822/src/vs/editor/browser/widget/codeEditorWidget.ts#L427) and the `getModel` here will return `null` every time.
> Remove explicit model deletion

- src/editor.tsx
- src/utils.ts
Hi ! This is my first PR here. I am a front-end software developer. In the project I am currently working in we are using `react-monaco-editor` and noticed this behaviour. I employed this technique to pass in the latest reference of the onChange function without using any hooks.
Re-initializing `onDidChangeModelContent` doesn't seem necessary here every time onChange ref changes from the props since most people define handlers inside the render body itself. 
Fixes https://github.com/react-monaco-editor/react-monaco-editor/issues/704
> fix: stale onChange callback in onDidChangeModelContent handler

- src/types.ts
In "src\types.ts" file, I defined a type named "Them" as union " 'vs' |'vs-dark' | 'hc-black' ". 
I changed "them" in MonacoEditorBaseProps interface to "theme?:Theme | (string & {}) | null;" so now we can have partial autocomplete and TypeScript provide us  'vs' |'vs-dark' | 'hc-black' autocomplete and allows any other string.
> Add Them union type and activate partial autocomplete for it

- src/editor.tsx
- src/utils.ts
While tackling the problem of stale onChange callback, onChange was hooked into a global variable. And on each re-render this global variable was updated with the latest reference of the onChange. But this should have been through a ref object instead. This way individual MonacoEditor components will have their own references of onChange. 
Although React warns against writing to ref during renders this is safe since we are not using the ref in the rendering logic.
Fixes https://github.com/react-monaco-editor/react-monaco-editor/issues/964
> fix: using wrong onChange if multiple instances of monaco editor are mounted on the same screen

- README.md
- package.json
- src/diff.tsx
- src/editor.tsx
- src/types.ts
The change allows access to the MonacoEditor through the ref. This was mentioned in the README, but it looks like it got dropped at some point. 
The diff is better viewed with ignored whitespace. Let me know if there's anything I need to do. Thanks!
> Support refs for interacting with the MonacoEditor instance
