- src/index.js
This should be before the `onChange`
https://github.com/superRaytin/react-monaco-editor/issues/9
> fix: Undo Issue

- src/index.js
Merging back the changes from the vega fork. We should also merge #35
> Merge back changes from vega fork

- README.md
Set theme in options is no longer available，the Component has a new props: theme.
> add theme in README

- package.json
Update list of authors in alphabetical order
> Updated authors in package.json

- README.md
- src/diff.js
This PR adds a new component to support the diff functionality provided by Monaco.
The component is a modified version of the one done by @mattmichler and reported in the [issue](https://github.com/superRaytin/react-monaco-editor/issues/32#issuecomment-336227288) as a gist, with some fixes, which is a copy of the original component.
I will provide an example if needed.
> Diff Editor Component

- package.json
Same as https://github.com/superRaytin/react-monaco-editor/pull/57 but for the top level package.json.
See https://babeljs.io/env for context.
> migrate top-level package.json to babel-preset-env

- src/diff.js
- src/editor.js
> Update layout on size's change

- .npmignore
- package.json
Add src release, solve eslint import/no-unresolved error
#58
> Use npmignore to filter published files

- .eslintignore
- package.json
- src/index.d.ts
Addresses issue #114.
Eslint currently fails on the `.d.ts` file.
> Add basic type definitions

- .gitignore
- yarn.lock
> Upgrade react typings

- src/editor.js
fixes https://github.com/superRaytin/react-monaco-editor/issues/156
> fix update options

- README.md
Resolves https://github.com/superRaytin/react-monaco-editor/issues/139
> Add section about css modules conflict

- README.md
Hi,
without validate set to true, validation is not performed
> Fix docs of json schema validation

- package.json
- yarn.lock
Just upgrade monaco-editor to latest version
> Upgrade monaco-editor

- example/index.js
- src/diff.js
Fixed diff getValue() from modified "editor.getModel()" instead of editor instance.
> Diff: editor.getValue is not a function

- src/diff.js
Fixed destroying monaco instance on will unmount for both models "original, modified"
> Fixed destroying monaco instance on diff editor will unmount

- src/diff.js
- src/editor.js
- src/index.d.ts
Hi, I tried to this package, but I found an inconvenience point in "onChange".
Please, add an "onDidModelContent" event as a second argument in "onChange".
> Add a argument in onChange 

- src/index.d.ts
> Use IStandaloneEditorConstructionOptions for EditorWillMount

- README.md
> docs(readme): usage with create-react-app

- package.json
...not `lib/types.d.ts`.
Fixes #295.
> Fix: types should point to lib/index.d.ts

- README.md
- src/index.ts
fixes https://github.com/react-monaco-editor/react-monaco-editor/issues/314
> Export monaco-editor types for typescript

- src/diff.tsx
fix https://github.com/react-monaco-editor/react-monaco-editor/issues/332
> fix: modifiedEditor is undefined in monaco-editor(v0.22.3)

- .github/dependabot.yml
- .github/workflows/merge-dependabot.yml
- package.json
- yarn.lock
https://github.com/react-monaco-editor/react-monaco-editor/issues/356
> chore: use more specific monaco-editor version in dependencies

- example/package.json
- example/yarn.lock
- package.json
- yarn.lock
> chore: upgrade deps

- .eslintrc
- src/diff.tsx
- src/editor.tsx
Rebase components build way from classes to hooks.
> refactor: use hooks
